/**
 * Dataset de líneas de colectivo del AMBA.
 * Fuente: omnilineas.com.ar — ramales reales de cada línea.
 * Actualizado: 2026-04
 */
import type { BusLine } from '@/types'

function linea(number: string, branches?: { id: string; name: string }[]): BusLine {
  return {
    number,
    name: `Línea ${number}`,
    branches: branches ?? [{ id: `${number}-servicio`, name: 'Servicio' }],
  }
}

function b(lineNumber: string, id: string, name: string) {
  return { id: `${lineNumber}-${id}`, name }
}

export const BUS_LINES: BusLine[] = [
  linea('1', [
    b('1', 'a', 'A - Est. Morán'),
    b('1', 'b', 'B - Est. Morán'),
  ]),
  linea('2', [
    b('2', 'a', 'A - Lomas del Mirador'),
    b('2', 'b', 'B - Lomas del Mirador'),
  ]),
  linea('4', [
    b('4', 'a', 'A - Correo Central'),
    b('4', 'b', 'B - Dársena Sur'),
    b('4', 'c', 'C - Central Costanera S.A.'),
  ]),
  linea('5', [
    b('5', 'a', 'A - Retiro'),
    b('5', 'b', 'B - Retiro'),
  ]),
  linea('6', [
    b('6', 'a', 'A - Villa Soldati por Caseros'),
    b('6', 'b', 'B - Villa Soldati por Brasil'),
    b('6', 'c', 'C - Pompeya por Caseros'),
    b('6', 'd', 'D - Pompeya por Brasil'),
  ]),
  linea('7', [
    b('7', 'a', 'A - Parque Avellaneda'),
    b('7', 'b', 'B - Barrio Samore'),
  ]),
  linea('8', [
    b('8', 'a', 'A - Aeropuerto Ezeiza por Liniers'),
    b('8', 'b', 'B - Mercado Central por Liniers'),
    b('8', 'c', 'C - Liniers'),
    b('8', 'd', 'D - Semirapido Liniers por autopista'),
  ]),
  linea('9', [
    b('9', 'a', 'A - Caraza por Castro'),
    b('9', 'b', 'B - Caraza por Moreno'),
  ]),
  linea('10', [
    b('10', 'a', 'A - Wilde'),
  ]),
  linea('12', [
    b('12', 'a', 'A - Palermo'),
    b('12', 'b', 'B - Palermo'),
  ]),
  linea('15', [
    b('15', 'a', 'A - Est. Benavídez'),
    b('15', 'b', 'B - Est. Benavídez por Hospital Naval'),
    b('15', 'c', 'C - Est. Pacheco'),
    b('15', 'd', 'D - Don Torcuato'),
    b('15', 'e', 'E - Barrio 1º de Mayo'),
    b('15', 'f', 'F - Pte Saavedra'),
    b('15', 'g', 'G - Barrancas de Belgrano'),
    b('15', 'h', 'H - Est. Benavídez'),
    b('15', 'i', 'I - Est. Benavídez'),
    b('15', 'j', 'J - Est. Pacheco'),
    b('15', 'k', 'K - Hasta Ruta 202'),
    b('15', 'l', 'L - Fabrica Wobron'),
  ]),
  linea('17', [
    b('17', 'a', 'A - Wilde'),
  ]),
  linea('19', [
    b('19', 'a', 'A - Estación Carapachay'),
  ]),
  linea('20', [
    b('20', 'a', 'A - Esteban Echeverría por Virgen de Itatí'),
    b('20', 'b', 'B - Esteban Echeverría por Hornos'),
  ]),
  linea('21', [
    b('21', 'a', 'A - Rotonda Dardo Rocha'),
    b('21', 'b', 'B - Fábrica Ford'),
    b('21', 'c', 'C - Puente Saavedra'),
    b('21', 'd', 'D - Autopista Ing. Pascual Palazzo e Hipólito Yrigoyen'),
    b('21', 'e', 'E - Estación Tigre'),
    b('21', 'f', 'F - Estación Florida'),
    b('21', 'g', 'G - Cementerio de Olivos'),
    b('21', 'h', 'H - Puente Saavedra'),
    b('21', 'i', 'I - Puente Saavedra (Expreso)'),
    b('21', 'j', 'J - Fábrica Ford (Expreso)'),
    b('21', 'k', 'K - Autopista Ing. Pascual Palazzo y Av. Bernarbé Márquez'),
  ]),
  linea('22', [
    b('22', 'a', 'A - Quilmes'),
    b('22', 'b', 'B - Quilmes'),
  ]),
  linea('23', [
    b('23', 'a', 'A - Retiro'),
  ]),
  linea('24', [
    b('24', 'a', 'A - Wilde por Cementerio de Avellaneda'),
    b('24', 'b', 'B - Wilde por Lynch'),
  ]),
  linea('25', [
    b('25', 'a', 'A - Saenz Peña'),
  ]),
  linea('26', [
    b('26', 'a', 'A - Flores Sur'),
  ]),
  linea('28', [
    b('28', 'a', 'A - Pte. La Noria'),
    b('28', 'b', 'B - Liniers'),
    b('28', 'c', 'C - La Salada'),
    b('28', 'd', 'D - Ciudad Universitaria'),
    b('28', 'e', 'E - Estación Rivadavia'),
    b('28', 'f', 'F - Ciudad Universitaria'),
    b('28', 'g', 'G - La Salada'),
    b('28', 'h', 'H - Ciudad Universitaria'),
    b('28', 'i', 'I - Estación Rivadavia'),
    b('28', 'j', 'J - Ciudad Universitaria Expreso'),
    b('28', 'k', 'K - Ciudad Universitaria Expreso'),
    b('28', 'l', 'L - Liniers por Roca Expreso'),
  ]),
  linea('29', [
    b('29', 'a', 'A - Olivos'),
    b('29', 'b', 'B - Parque Sarmiento'),
    b('29', 'c', 'C - Estación Rivadavia'),
    b('29', 'd', 'D - Estación Belgrano C'),
  ]),
  linea('31', [
    b('31', 'a', 'A - Barrio 9 de Abril por Calle 11'),
    b('31', 'b', 'B - Barrio 9 de Abril por Calle 21'),
    b('31', 'c', 'C - Ingeniero Budge por Calle 11'),
    b('31', 'd', 'D - Ingeniero Budge por Calle 21'),
  ]),
  linea('32', [
    b('32', 'a', 'A - Estación Lanús'),
    b('32', 'b', 'B - Barrio 9 de Abril'),
    b('32', 'c', 'C - Barrio 9 de Abril'),
    b('32', 'd', 'D - Isaac Newton y Epecuén'),
    b('32', 'e', 'E - Ingeniero Budge'),
  ]),
  linea('33', [
    b('33', 'c-barracas', 'C - por Barracas'),
    b('33', 'c-barracas-retiro', 'C - por Barracas (desde Retiro)'),
    b('33', 'c-dock', 'C - por Dock Sud'),
    b('33', 'c-dock-retiro', 'C - por Dock Sud (desde Retiro)'),
    b('33', 'escalada', 'Est. Remedios de Escalada'),
    b('33', 'm-barracas', 'M - por Barracas'),
    b('33', 'm-barracas-retiro', 'M - por Barracas (desde Retiro)'),
    b('33', 'm-dock', 'M - por Dock Sud'),
    b('33', 'm-dock-retiro', 'M - por Dock Sud (desde Retiro)'),
  ]),
  linea('34', [
    b('34', 'a', 'A - Estación Liniers'),
    b('34', 'b', 'B - Estación Liniers'),
    b('34', 'c', 'C - Estación Liniers'),
    b('34', 'd', 'D - Estación Liniers Expreso'),
    b('34', 'e', 'E - Estación Liniers Expreso'),
  ]),
  linea('36', [
    b('36', 'a', 'A - Villa Celina'),
    b('36', 'b', 'B - Puente de La Noria'),
  ]),
  linea('37', [
    b('37', 'a', 'A - Lanús por Gimnasia y Esgrima'),
    b('37', 'b', 'B - Lanús por Aeroparque Newberry'),
    b('37', 'c', 'C - Lanús'),
  ]),
  linea('39', [
    b('39', 'a', 'A - Chacarita por Plaza Italia'),
    b('39', 'b', 'B - Chacarita por Plaza Italia'),
    b('39', 'c', 'C - Chacarita por Plaza Serrano'),
  ]),
  linea('41', [
    b('41', 'a', 'A - Munro por Viaducto Carapachay'),
    b('41', 'b', 'B - Munro por Dorrego'),
  ]),
  linea('42', [
    b('42', 'a', 'A - Ciudad Universitaria por Lugones'),
    b('42', 'b', 'B - Ciudad Universitaria por La Pampa'),
    b('42', 'c', 'C - Ciudad Universitaria por Lugones Expreso'),
    b('42', 'd', 'D - Ciudad Universitaria por La Pampa Expreso'),
  ]),
  linea('44', [
    b('44', 'a', 'A - Barrancas de Belgrano'),
  ]),
  linea('45', [
    b('45', 'a', 'A - Remedios de Escalada'),
    b('45', 'b', 'B - Remedios de Escalada Expreso'),
    b('45', 'c', 'C - Constitución Expreso'),
    b('45', 'd', 'D - Retiro Expreso'),
  ]),
  linea('46', [
    b('46', 'a', 'A - Universidad La Matanza por Barrio Espora'),
    b('46', 'b', 'B - Universidad La Matanza por Av. Iriarte'),
  ]),
  linea('47', [
    b('47', 'a', 'A - Autódromo por Nogoyá'),
    b('47', 'b', 'B - Autódromo por Camarones'),
    b('47', 'c', 'C - Est. Liniers Expreso'),
  ]),
  linea('49', [
    b('49', 'b', 'B - Isidro Casanova por Peribebuy'),
  ]),
  linea('50', [
    b('50', 'a', 'A - Eva Perón y Gral. Paz'),
    b('50', 'b', 'B - Hospital Piñero'),
  ]),
  linea('51', [
    b('51', 'a', 'A - Cañuelas por RN 205'),
    b('51', 'b', 'B - Canning por RN 205'),
    b('51', 'c', 'C - Aeropuerto Ezeiza por RN 205'),
    b('51', 'd', 'D - Aeropuerto Ezeiza por Av. Fair'),
    b('51', 'e', 'E - Brandsen'),
    b('51', 'f', 'F - Alejandro Korn'),
    b('51', 'g', 'G - Máximo Paz por RN 205'),
    b('51', 'h', 'H - Estación Rafael Calzada'),
  ]),
  linea('53', [
    b('53', 'a', 'A - San Miguel'),
    b('53', 'b', 'B - El Palomar'),
    b('53', 'c', 'C - José C. Paz'),
    b('53', 'd', 'D - Nazca y Rivadavia'),
    b('53', 'e', 'E - José C. Paz Expreso'),
  ]),
  linea('55', [
    b('55', 'a', 'A - Don Bosco por San Justo'),
    b('55', 'b', 'B - Don Bosco por Rotonda San Justo'),
    b('55', 'c', 'C - Rotonda San Justo Expreso'),
  ]),
  linea('56', [
    b('56', 'a', 'A - Tapiales'),
    b('56', 'b', 'B - Est. Varela'),
    b('56', 'c', 'C - Ciudad Evita'),
    b('56', 'd', 'D - Ciudad Evita Expreso'),
  ]),
  linea('57'),
  linea('59', [
    b('59', '1', '1 - La Lucila'),
    b('59', '2', '2 - Barrio Golf por Autopista'),
    b('59', 'est', 'Est. Del Valle'),
  ]),
  linea('60', [
    b('60', 'c', 'C - Est. Aristóbulo del Valle'),
    b('60', 'f', 'F - Alto Tigre por Alto San Isidro'),
    b('60', 'g', 'G - Est. Aristóbulo del Valle'),
    b('60', 'h', 'H - Bajo Tigre por Alto San Isidro'),
    b('60', 'i', 'I - Alto Tigre por Bajo San Isidro'),
    b('60', 'j', 'J - Tigre por Autopista y Acceso Norte'),
    b('60', 'k', 'K - Tigre por Autopista y Acceso Norte R24 Larghi'),
    b('60', 'l', 'L - Tigre por Larralde Ruta 24'),
    b('60', 'm', 'M - Alto Tigre por Acceso Norte'),
    b('60', 'n', 'N - Alto Tigre por Acceso Norte'),
    b('60', 'o', 'O - Bajo Tigre por Fleming'),
    b('60', 'p', 'P - Escobar por Ruta 24 y Larghi'),
    b('60', 'q', 'Q - Escobar por Autopista'),
    b('60', 'r', 'R - Escobar por Autopista y Boulogne Sur Mer'),
    b('60', 's', 'S - Escobar por Autopista y Boulogne Sur Mer'),
    b('60', 't', 'T - Escobar por Ruta 27 y Larghi'),
    b('60', 'u', 'U - Escobar por Ruta 24 y Larghi'),
    b('60', 'v', 'V - Escobar por Autopista Expreso Diferencial'),
    b('60', 'w', 'W - Escobar por Autopista Expreso Diferencial'),
    b('60', 'nn', 'Ñ - Bajo Tigre por Fleming'),
  ]),
  linea('61', [
    b('61', 'a', 'A - Retiro - Constitución Circular'),
    b('61', 'b', 'B - Retiro - Constitución Circular por UCA'),
  ]),
  linea('62', [
    b('62', 'a', 'A - Retiro - Constitución Circular'),
    b('62', 'b', 'B - Retiro - Constitución Circular por UCA'),
  ]),
  linea('63', [
    b('63', 'a', 'A - Ciudad Madero por Torre'),
    b('63', 'b', 'B - Ciudad Madero por Pagola'),
  ]),
  linea('64', [
    b('64', 'a', 'A - Barrancas de Belgrano por Hospital Militar'),
    b('64', 'b', 'B - Barrancas de Belgrano por Hipódromo'),
    b('64', 'c', 'C - Barrancas de Belgrano por Hospital Militar y UCA'),
    b('64', 'd', 'D - Barrancas de Belgrano por Hipódromo y UCA'),
    b('64', 'e', 'E - Barrancas de Belgrano por Hospital Militar'),
    b('64', 'f', 'F - Barrancas de Belgrano por Hipódromo'),
  ]),
  linea('65', [
    b('65', 'a', 'A - Barrancas de Belgrano'),
  ]),
  linea('67', [
    b('67', 'a', 'A - Munro'),
    b('67', 'b', 'B - Munro por Dorrego'),
  ]),
  linea('68', [
    b('68', 'a', 'A - Puente Saavedra por Carranza'),
    b('68', 'b', 'B - Puente Saavedra por Dorrego'),
  ]),
  linea('70', [
    b('70', 'a', 'A - Retiro'),
    b('70', 'b', 'B - Retiro'),
  ]),
  linea('71', [
    b('71', 'a', 'A - Maipú por Crisólogo Larralde'),
    b('71', 'b', 'B - Maipú por Autopista Ing. Pascual Palazzo'),
    b('71', 'c', 'C - Maipú por Congreso'),
  ]),
  linea('74', [
    b('74', 'a', 'A - Longchamps'),
  ]),
  linea('75', [
    b('75', 'a', 'A - Lanús por Colombres'),
    b('75', 'b', 'B - Lanús por Hospital Penna'),
  ]),
  linea('76', [
    b('76', 'a', 'A - Saavedra por F.F. de la Cruz'),
    b('76', 'b', 'B - Saavedra por Janer'),
  ]),
  linea('78', [
    b('78', 'a', 'A - Villa Adelina por Charlone'),
    b('78', 'b', 'B - Villa Adelina por Chilavert'),
    b('78', 'c', 'C - Loma Hermosa'),
  ]),
  linea('79', [
    b('79', 'a', 'A - San Vicente'),
    b('79', 'b', 'B - Villa Numancia'),
    b('79', 'c', 'C - Guernica'),
    b('79', 'd', 'D - Longchamps'),
    b('79', 'e', 'E - Est. Varela por Lacaze'),
    b('79', 'f', 'F - Est. Varela por Av. Eva Perón'),
    b('79', 'g', 'G - Claypole'),
    b('79', 'h', 'H - Barrio Rayo de Sol'),
    b('79', 'i', 'I - Barrio San José'),
    b('79', 'j', 'J - Calzada - Constitución Circular'),
  ]),
  linea('80', [
    b('80', 'a', 'A - Barrio Sarmiento'),
    b('80', 'b', 'B - Barrio Sarmiento por Piedrabuena'),
    b('80', 'c', 'C - Barrio Sarmiento'),
    b('80', 'd', 'D - Barrio Sarmiento por Piedrabuena'),
    b('80', 'e', 'E - Liniers Expreso'),
  ]),
  linea('84', [
    b('84', 'a', 'A - Villa del Parque'),
  ]),
  linea('85', [
    b('85', 'a', 'A - Ciudadela Norte por Pte Aguero'),
    b('85', 'g', 'G - Ciudadela Norte por Pte Gerli'),
    b('85', 'i', 'I - Ciudadela Norte por Pte Gerli'),
  ]),
  linea('86', [
    b('86', 'a', 'A - G.Catán por Laguna y RN3'),
    b('86', 'b', 'B - G.Catán por Autopista y RN3 Expreso'),
    b('86', 'c', 'C - G.Catán por Autopista y RP21 Expreso'),
    b('86', 'd', 'D - G.Catán por Laguna y RN3 Expreso'),
    b('86', 'e', 'E - G.Catán por Laguna y RP21 Expreso'),
    b('86', 'f', 'F - Villegas por Laguna'),
  ]),
  linea('87', [
    b('87', 'a', 'A - Fábrica Ford'),
    b('87', 'b', 'B - Italia y San José'),
    b('87', 'c', 'C - Barrio San Isidro'),
  ]),
  linea('88', [
    b('88', 'a', 'A - Lobos por Rivadavia'),
    b('88', 'b', 'B - Lobos por Alberdi'),
    b('88', 'c', 'C - Cañuelas por Rivadavia y RN205'),
    b('88', 'd', 'D - Cañuelas por Alberdi y RN205'),
    b('88', 'e', 'E - KM 56 RN3 por Rivadavia'),
    b('88', 'f', 'F - KM 56 RN3 por Alberdi'),
    b('88', 'g', 'G - KM 48 RN3 por Rivadavia'),
    b('88', 'h', 'H - KM 48 RN3 por Alberdi'),
    b('88', 'i', 'I - KM 35 RN3 por Rivadavia'),
    b('88', 'j', 'J - KM 35 RN3 por Alberdi'),
    b('88', 'k', 'K - KM 26 RN3 por Rivadavia'),
    b('88', 'l', 'L - KM 26 RN3 por Alberdi'),
    b('88', 'm', 'M - KM 29 RN3 por Autopista y Bufano Expreso'),
    b('88', 'n', 'N - KM 48 RN3 por Autopista y Gral.Rojo Expreso'),
  ]),
  linea('90', [
    b('90', 'a', 'A - Est. Lacroze'),
    b('90', 'b', 'B - Villa Devoto'),
  ]),
  linea('91', [
    b('91', 'a', 'A - Villegas por Barrio Sarmiento'),
    b('91', 'b', 'B - Villegas por Juan Rava'),
    b('91', 'c', 'C - Villegas por Juan Rava'),
    b('91', 'd', 'D - Villegas por Barrio Sarmiento'),
    b('91', 'e', 'E - Villegas por Juan Rava'),
    b('91', 'f', 'F - Villegas por Autopista Expreso'),
  ]),
  linea('92', [
    b('92', 'a', 'A - Olimpo y Cintura'),
    b('92', 'b', 'B - Puente 12'),
    b('92', 'c', 'C - Gral.Paz y Perón'),
  ]),
  linea('93', [
    b('93', 'a', 'A - Avellaneda'),
    b('93', 'b', 'B - Avellaneda por Sávori'),
    b('93', 'c', 'C - Avellaneda'),
  ]),
  linea('95', [
    b('95', 'a', 'A - Avellaneda'),
    b('95', 'b', 'B - Avellaneda'),
  ]),
  linea('96', [
    b('96', 'a', 'A - Pontevedra por Rivadavia'),
    b('96', 'aa', 'AA - Pontevedra por Autopista Expreso'),
    b('96', 'ab', 'AB - Pontevedra por Alberdi Expreso'),
    b('96', 'ac', 'AC - Rafael Castillo por Autopista Expreso'),
    b('96', 'ad', 'AD - Barrio San Alberto por Autopista Expreso'),
    b('96', 'ae', 'AE - Villa Scasso por Autopista Expreso'),
    b('96', 'af', 'AF - Villa Scasso por Alberdi Expreso'),
    b('96', 'ag', 'AG - Barrio Esperanza por Autopista Expreso'),
    b('96', 'ah', 'AH - Est. Laferrere por Autopista Expreso'),
    b('96', 'b', 'B - González Catán por KM32 RN3'),
    b('96', 'c', 'C - Rafael Castillo por Rivadavia'),
    b('96', 'd', 'D - Barrio San Alberto por Rivadavia'),
    b('96', 'e', 'E - Barrio La Foresta'),
    b('96', 'f', 'F - Villa Scasso por Rivadavia'),
    b('96', 'g', 'G - Barrio Esperanza por Rivadavia'),
    b('96', 'h', 'H - Est. Laferrere por Rivadavia y KM24.7 RN3'),
    b('96', 'i', 'I - Est. Laferrere por Rivadavia y KM26 RN3'),
    b('96', 'r', 'R - Pontevedra'),
    b('96', 's', 'S - González Catán por KM32 RN3'),
    b('96', 't', 'T - Rafael Castillo'),
    b('96', 'u', 'U - Barrio San Alberto'),
    b('96', 'v', 'V - Barrio La Foresta'),
    b('96', 'w', 'W - Villa Scasso'),
    b('96', 'x', 'X - Barrio Esperanza'),
    b('96', 'y', 'Y - Est. Laferrere por Rivadavia y KM24.7 RN3'),
    b('96', 'z', 'Z - Est. Laferrere por Rivadavia y KM26 RN3'),
    b('96', 'nn', 'Ñ - Villa Scasso por Rivadavia'),
  ]),
  linea('97', [
    b('97', 'a', 'A - Estación Morón'),
    b('97', 'b', 'B - Mercado Central'),
    b('97', 'c', 'C - Barrio San Alberto'),
  ]),
  linea('98', [
    b('98', '1', '1 - Balneario de Quilmes por Las Flores'),
    b('98', '116', '116 - Barrio Gráfico'),
    b('98', '2', '2 - Balneario de Quilmes por Montevideo'),
    b('98', '3', '3 - Villa España por Calchaquí'),
    b('98', '5', '5 - Villa España por Ramón Franco'),
  ]),
  linea('99', [
    b('99', 'a', 'A - Correo Central'),
  ]),
  linea('100', [
    b('100', 'a', 'A - Est. Lanús por Pavón'),
    b('100', 'b', 'B - Est. Lanús por Guemes'),
    b('100', 'c', 'C - Roma y Lynch'),
    b('100', 'd', 'D - Roma y Lynch Expreso'),
  ]),
  linea('101', [
    b('101', 'a', 'A - Retiro por Flores'),
    b('101', 'b', 'B - Retiro por Villa Soldati'),
    b('101', 'c', 'C - Retiro'),
  ]),
  linea('102', [
    b('102', 'a', 'A - Barracas'),
  ]),
  linea('103', [
    b('103', 'a', 'A - Estacion Tapiales'),
    b('103', 'b', 'B - Mataderos'),
    b('103', 'c', 'C - Estacion Tapiales'),
    b('103', 'd', 'D - Primera Junta'),
  ]),
  linea('104'),
  linea('105', [
    b('105', 'a', 'A - Sáenz Peña por Santos Lugares'),
    b('105', 'b', 'B - Sáenz Peña por Golf'),
  ]),
  linea('106', [
    b('106', 'a', 'A - Retiro'),
  ]),
  linea('107', [
    b('107', 'a', 'A - Ciudad Universitaria por Libertador'),
    b('107', 'b', 'B - Ciudad Universitaria por Alcorta'),
  ]),
  linea('108', [
    b('108', 'a', 'A - Retiro'),
  ]),
  linea('109', [
    b('109', 'a', 'A - Correo Central por Hospital'),
    b('109', 'b', 'B - Correo Central'),
    b('109', 'c', 'C - Correo Central por Córdoba Expreso'),
  ]),
  linea('110', [
    b('110', 'a', 'A - Villa Martelli por Saavedra'),
    b('110', 'b', 'B - Villa Martelli por Constituyentes'),
  ]),
  linea('111', [
    b('111', 'a', 'A - J.L.Suárez por V.Concepción'),
    b('111', 'b', 'B - J.L.Suárez por Constituyentes'),
    b('111', 'c', 'C - J.L.Suárez por V.Concepción y Paraguay'),
    b('111', 'd', 'D - Chacarita'),
    b('111', 'e', 'E - Constituyentes y Gral.Paz'),
    b('111', 'f', 'F - Constituyentes y Gral.Paz por Paraguay'),
  ]),
  linea('112'),
  linea('113', [
    b('113', 'a', 'A - San Justo por Boyaca'),
    b('113', 'b', 'B - San Justo por Artigas'),
  ]),
  linea('114', [
    b('114', 'a', 'A - Pte. La Noria'),
    b('114', 'b', 'B - Pte. La Noria por Parque de la Ciudad'),
    b('114', 'c', 'C - Cnel. Roca y Saladillo'),
  ]),
  linea('115', [
    b('115', 'a', 'A - Soldati'),
    b('115', 'b', 'B - Once'),
  ]),
  linea('117', [
    b('117', 'a', 'A - Ing. Budge por Recondo'),
    b('117', 'b', 'B - Juan XXIII'),
  ]),
  linea('118', [
    b('118', 'a', 'A - Barrancas de Belgrano'),
    b('118', 'b', 'B - Barrancas de Belgrano'),
  ]),
  linea('119'),
  linea('123', [
    b('123', 'a', 'A - Palomar'),
  ]),
  linea('124', [
    b('124', 'a', 'A - Sáenz Peña, Devoto'),
    b('124', 'b', 'B - Baigorria y Nazca'),
  ]),
  linea('126', [
    b('126', 'a', 'A - Alberti y República de Chile'),
    b('126', 'b', 'B - Cementerio Villegas'),
    b('126', 'c', 'C - Alberti y República de Chile'),
    b('126', 'd', 'D - Cementerio Villegas'),
  ]),
  linea('127', [
    b('127', 'a', 'A - Panamericana y Calle 202'),
  ]),
  linea('128', [
    b('128', 'a', 'A - Valentín Alsina'),
  ]),
  linea('129', [
    b('129', 'n', 'N - La Plata por Centenario'),
    b('129', 'o', 'O - La Plata por Centenario'),
    b('129', 'p', 'P - La Plata por Autopista Expreso'),
    b('129', 'q', 'Q - La Plata por Autopista Expreso'),
    b('129', 'r', 'R - La Plata por Autopista Expreso'),
  ]),
  linea('130', [
    b('130', 'a', 'A - Est. Boulogne por Munro'),
    b('130', 'b', 'B - Est. Boulogne por Panamericana'),
  ]),
  linea('132', [
    b('132', 'a', 'A - Retiro por Carabobo'),
    b('132', 'b', 'B - Retiro por Plaza Pueyrredón'),
    b('132', 'c', 'C - Retiro desde Plaza de Miserere'),
  ]),
  linea('133', [
    b('133', 'a', 'A - Florida'),
    b('133', 'b', 'B - Gaona y Nazca'),
    b('133', 'c', 'C - Florida'),
    b('133', 'd', 'D - Est. Vicente López'),
  ]),
  linea('134', [
    b('134', 'a', 'A - Barrio Nicolás Avellaneda'),
    b('134', 'b', 'B - Plaza Pueyrredón'),
  ]),
  linea('135', [
    b('135', 'a', 'A - Valentín Alsina'),
  ]),
  linea('136', [
    b('136', 'a', 'A - Navarro'),
    b('136', 'b', 'B - Marcos Paz'),
    b('136', 'c', 'C - Parque San Martín'),
    b('136', 'd', 'D - Marcos Paz'),
  ]),
  linea('140', [
    b('140', 'a', 'A - Est. Boulogne'),
    b('140', 'b', 'B - Av. Lacroze'),
    b('140', 'c', 'C - Est. Urquiza'),
    b('140', 'd', 'D - Congreso y Bucarelli'),
  ]),
  linea('141', [
    b('141', 'a', 'A - Villa Albertina por Piedrabuena'),
    b('141', 'b', 'B - Villa Albertina por Barrio Savio'),
    b('141', 'c', 'C - Villa Albertina Expreso'),
  ]),
  linea('143', [
    b('143', 'a', 'A - Tapiales por Chilavert'),
    b('143', 'b', 'B - Tapiales por Juan Rava'),
    b('143', 'c', 'C - Tapiales por Chilavert y UCA'),
    b('143', 'd', 'D - Tapiales por Juan Rava y UCA'),
    b('143', 'e', 'E - Tapiales por Chilavert y de la Cruz'),
    b('143', 'f', 'F - Puente La Noria'),
    b('143', 'g', 'G - Villa Celina por Chilavert'),
    b('143', 'h', 'H - Tapiales por Juan Rava y de la Cruz'),
    b('143', 'i', 'I - Villa Celina por Juan Rava'),
  ]),
  linea('146', [
    b('146', 'a', 'A - Ciudadela Norte'),
    b('146', 'b', 'B - Hasta Gral.Paz y Beiro'),
  ]),
  linea('148', [
    b('148', 'b', 'B - El Jalón'),
    b('148', 'c-alpino', 'C - Alpino por Senzabello'),
    b('148', 'c-cementerio', 'C - Cementerio'),
    b('148', 'c-capilla', 'C - La Capilla'),
    b('148', 'h', 'H - Villa del Plata'),
  ]),
  linea('150', [
    b('150', 'a', 'A - Villa Madero por Est. Sáenz'),
    b('150', 'b', 'B - Villa Madero por Hospital Aeronáutico'),
  ]),
  linea('151', [
    b('151', 'a', 'A - Puente Saavedra'),
  ]),
  linea('152', [
    b('152', 'a', 'A - Olivos'),
    b('152', 'b', 'B - Olivos por UCA'),
    b('152', 'c', 'C - Est. Mitre'),
    b('152', 'd', 'D - Olivos Expreso'),
  ]),
  linea('153', [
    b('153', 'a', 'A - Barrio Nuevo'),
  ]),
  linea('154', [
    b('154', 'a', 'A - Est. Lanús'),
  ]),
  linea('158', [
    b('158', 'a', 'A - Est. Lanús'),
  ]),
  linea('159', [
    b('159', 'a', 'A - Rotonda Juan María Gutiérrez'),
    b('159', 'b', 'B - Rotonda Juan María Gutiérrez'),
    b('159', 'c', 'C - Pueblo Nuevo'),
    b('159', 'd', 'D - Cruce Florencio Varela'),
    b('159', 'e', 'E - Estación Berazategui'),
    b('159', 'f', 'F - Barrio Gráfico'),
    b('159', 'g', 'G - Cruce Florencio Varela'),
    b('159', 'h', 'H - Barrio Gráfico Expreso'),
    b('159', 'i', 'I - Av. Rigolleau y Camino General Belgrano'),
  ]),
  linea('160', [
    b('160', 'a', 'A - Barrio Don Orione por Aysa y Alsina'),
    b('160', 'b', 'B - Barrio Don Orione por Aysa y Gonzalez'),
    b('160', 'c', 'C - Barrio Don Orione por Aeroparque y Alsina'),
    b('160', 'd', 'D - Barrio Don Orione por Aeroparque y Gonzalez'),
    b('160', 'e', 'E - Barrio Don Orione por Alsina'),
    b('160', 'f', 'F - Barrio Don Orione por Gonzalez'),
    b('160', 'g', 'G - Nueva Pompeya por Aysa'),
    b('160', 'h', 'H - Nueva Pompeya por Aeroparque'),
    b('160', 'k', 'K - Est. Lanús por Aysa'),
    b('160', 'l', 'L - Est. Lanús por Aeroparque'),
    b('160', 'n', 'N - Ciudad Universitaria por Aysa Expreso'),
  ]),
  linea('161', [
    b('161', 'a', 'A - Liniers por Florida'),
    b('161', 'b', 'B - Liniers por Martelli'),
  ]),
  linea('163', [
    b('163', 'b', 'B - San Miguel'),
  ]),
  linea('165', [
    b('165', 'a', 'A - Monte Grande por Boul.BsAs'),
    b('165', 'b', 'B - Monte Grande por San Martín'),
    b('165', 'c', 'C - Burzaco por Temperley'),
    b('165', 'd', 'D - Loma Verde por Garibaldi'),
    b('165', 'e', 'E - Estación Monte Grande'),
    b('165', 'f', 'F - Monte Grande por Boul.BsAs Expreso'),
  ]),
  linea('166', [
    b('166', 'a', 'A - Barrio Nuevo por Haedo'),
    b('166', 'b', 'B - Morón por Gaona'),
    b('166', 'c', 'C - Morón por Gaona'),
  ]),
  linea('168', [
    b('168', 'a', 'A - San Isidro'),
    b('168', 'b', 'B - Puente Saavedra por Córdoba'),
    b('168', 'c', 'C - Puente Saavedra por Concepción Arenal'),
    b('168', 'd', 'D - Villa Devoto'),
    b('168', 'e', 'E - Estacion Federico Lacroze'),
    b('168', 'f', 'F - Avenida Córdoba y Darwin'),
  ]),
  linea('169', [
    b('169', 'a', 'A - Loma Hermosa por Est.Coronado'),
    b('169', 'b', 'B - Loma Hermosa por Est.Podestá'),
  ]),
  linea('172', [
    b('172', 'a', 'A - Atalaya por Barrio La Marina'),
    b('172', 'b', 'B - Atalaya por Ing. Brian'),
  ]),
  linea('174', [
    b('174', 'a', 'A - Laferrere por Humboldt'),
    b('174', 'b', 'B - Isidro Casanova'),
    b('174', 'c', 'C - Ciudad Evita'),
    b('174', 'd', 'D - Est. Morón'),
    b('174', 'e', 'E - Rafael Castillo por Cristianía'),
    b('174', 'f', 'F - Rafael Castillo por Marconi'),
    b('174', 'g', 'G - Est. Rafael Castillo'),
  ]),
  linea('175', [
    b('175', 'a', 'A - Loma Hermosa'),
  ]),
  linea('176', [
    b('176', 'a', 'A - Est. Escobar'),
    b('176', 'b', 'B - Est. Escobar'),
    b('176', 'c', 'C - Pilar'),
    b('176', 'd', 'D - Cruce José C. Paz'),
    b('176', 'e', 'E - Est. Tortuguitas'),
    b('176', 'f', 'F - Barrio Primero de Mayo por San Martín'),
    b('176', 'g', 'G - Fábrica Eaton'),
    b('176', 'h', 'H - Fábrica Eaton'),
    b('176', 'i', 'I - Cruce Jose C. Paz'),
    b('176', 'j', 'J - Barrio Primero de Mayo'),
    b('176', 'k', 'K - Est. Escobar'),
    b('176', 'l', 'L - Pilar'),
    b('176', 'm', 'M - Est. Tortuguitas'),
    b('176', 'n', 'N - Corbeta La Uruguay y Tegucigalpa'),
    b('176', 'nn', 'Ñ - Parque Industrial Pilar Expreso'),
  ]),
  linea('177', [
    b('177', 'a', 'A - Est. Burzaco por Lacaze'),
    b('177', 'b', 'B - Est. Burzaco por Av. Eva Perón'),
  ]),
  linea('178', [
    b('178', 'b', 'B - Zeballos por Mitre'),
    b('178', 'c-roja', 'C Roja - Varela por Pte.Gerli y Senzabello'),
    b('178', 'c-verde', 'C Verde - Varela por Pte.Gerli y H.Yrigoyen'),
    b('178', 'g', 'G - Zeballos por Larralde'),
  ]),
  linea('179', [
    b('179', 'a', 'A - Estación Fiorito'),
    b('179', 'b', 'B - Cementerio de Lomas de Zamora'),
    b('179', 'c', 'C - Barrio San José'),
  ]),
  linea('180', [
    b('180', 'a', 'A - González Catán'),
    b('180', 'b', 'B - González Catán por Laferrere'),
    b('180', 'c', 'C - González Catán por Barrio San Alberto'),
    b('180', 'd', 'D - San Justo por Necochea'),
    b('180', 'e', 'E - González Catán por Laferrere'),
    b('180', 'f', 'F - González Catán por Barrio San Alberto'),
    b('180', 'h', 'H - González Catán por Laferrere Expreso'),
    b('180', 'i', 'I - González Catán por Barrio San Alberto Expreso'),
  ]),
  linea('181', [
    b('181', 'a', 'A - Ramos Mejía por La Merced'),
    b('181', 'b', 'B - Ramos Mejía por Puán'),
  ]),
  linea('182', [
    b('182', 'a', 'A - José C. Paz por Rosales'),
    b('182', 'b', 'B - José C. Paz por Marconi'),
    b('182', 'c', 'C - El Palomar por Emaús'),
    b('182', 'd', 'D - El Palomar por Villa Basso'),
  ]),
  linea('184', [
    b('184', 'a', 'A - Villa Adelina'),
  ]),
  linea('185', [
    b('185', 'a', 'A - Liniers'),
    b('185', 'b', 'B - Isidro Casanova'),
    b('185', 'c', 'C - Isidro Casanova'),
  ]),
  linea('188', [
    b('188', 'a', 'A - Estación Ingeniero Budge'),
    b('188', 'b', 'B - Camino de Cintura y Prof. A. Maxer'),
    b('188', 'e', 'E - Est. Terminal Puente de la Noria'),
    b('188', 'f', 'F - Eva Perón y Villa de Luján'),
    b('188', 'g', 'G - Estación Ingeniero Budge'),
  ]),
  linea('193', [
    b('193', 'a', 'A - Est. Laferrere por Laferrere Norte'),
    b('193', 'b', 'B - Est. Laferrere por Laferrere Sur'),
    b('193', 'c', 'C - Est. Independencia'),
  ]),
  linea('194', [
    b('194', 'a', 'A - Zárate'),
    b('194', 'b', 'B - Est. Escobar'),
    b('194', 'c', 'C - Est. Matheu'),
    b('194', 'd', 'D - Zárate'),
    b('194', 'e', 'E - Zárate'),
    b('194', 'f', 'F - Est. Escobar'),
    b('194', 'g', 'G - Zárate'),
    b('194', 'h', 'H - Lima'),
  ]),
  linea('195', [
    b('195', 'a', 'A - La Plata por Av. Mitre'),
    b('195', 'b', 'B - La Plata por Constitución y Autopista'),
    b('195', 'c', 'C - La Plata por Alem y Autopista'),
    b('195', 'd', 'D - La Plata por Alem y Autopista'),
    b('195', 'e', 'E - La Plata por Autopista'),
    b('195', 'f', 'F - La Plata por Constitución y Autopista'),
    b('195', 'g', 'G - La Plata por Constitución y Autopista Expreso'),
    b('195', 'h', 'H - La Plata por Alem y Autopista Expreso'),
    b('195', 'i', 'I - La Plata por Autopista Expreso'),
  ]),

  // ── Líneas GBA / suburbanas ──────────────────────────────────────────
  linea('203', [
    b('203', '1', 'Pilar por Del Viso'),
    b('203', '2', 'Pilar por Peaje'),
    b('203', '3', 'Por San Fernando a Estacion Moreno'),
    b('203', '4', 'Por Virreyes a Estacion Moreno'),
    b('203', '5', 'Por Panamericana a Est. Moreno'),
    b('203', '6', 'Ramal Ford a Est. Pilar'),
    b('203', '7', 'Ramal Pilar a Est. Pilar'),
    b('203', '8', 'Savio por Peaje'),
  ]),
  linea('204A', [
    b('204A', 'a', 'A - Av. San Martin y Gral. Paz a Fca Ford'),
    b('204A', 'b', 'B - Av. San Martin y Gral. Paz a Canal San Fernando'),
    b('204A', 'c', 'C - Barrio Carupa a Zarate'),
  ]),
  linea('204B', [
    b('204B', '1', 'Barrio Carupa a Estacion Garin'),
  ]),
  linea('205', [
    b('205', '1', 'Liniers a Pontevedra'),
  ]),
  linea('218', [
    b('218', '1', 'Estacion Cañuelas'),
    b('218', '2', 'Estacion Cañuelas por Miller'),
    b('218', '3', 'Gonzalez Catan'),
  ]),
  linea('219', [
    b('219', 'negro', 'Negro - Alpargatas'),
    b('219', 'rojo', 'Rojo - El Carmen'),
    b('219', '3', 'por Calle 138'),
  ]),
  linea('228a', [
    b('228a', '1', 'Zarate'),
  ]),
  linea('228b', [
    b('228b', '1', 'Escobar'),
    b('228b', '2', 'Escobar - Servicio directo'),
  ]),
  linea('228d', [
    b('228d', '1', 'Garin - Ramal por Lopez Carmelo'),
    b('228d', '2', 'Garin - Ramal por Lopez Carmelo - Cabot'),
    b('228d', '3', 'Garin - Servicio Semi-Rapido'),
  ]),
  linea('228e', [
    b('228e', '1', 'Garin - Ramal por Lopez Camelo'),
    b('228e', '2', 'Garin - Ramal por Lopez Carmelo - Cabot'),
    b('228e', '3', 'Garin - Servicio Semi-Rapido'),
  ]),
  linea('228f', [
    b('228f', '1', 'Del Viso'),
  ]),
  linea('236', [
    b('236', '1', 'Barrio Belgrano'),
    b('236', '2', 'Barrio Rivadavia - Barrio Matera - Est. Merlo'),
    b('236', '3', 'Gonzales Catan'),
    b('236', '4', 'Laferrere'),
    b('236', '5', 'Los Aromos'),
    b('236', '6', 'Marcos Paz'),
    b('236', '7', 'Pontevedra'),
    b('236', '8', 'San Francisco'),
  ]),
  linea('237', [
    b('237', '1', 'Cartel blanco - Beiro y Av. Gral Paz'),
    b('237', '2', 'Ramal A - Cartel Amarillo - Hurlingham - W. C. Morris'),
    b('237', '3', 'Ramal B - Cartel Rojo - Liniers por Caseros'),
    b('237', '4', 'Ramal Caseros - Puerta 8 por Palomar'),
  ]),
  linea('238', [
    b('238', '1', 'Fracc. Moron por Libertad - La Teja'),
    b('238', '2', 'Ramal Barrio San Juan - Merlo Gomez'),
    b('238', '3', 'Ramal Distrito Militar por Libertad - La Teja'),
    b('238', '4', 'Ramal Haedo Barrio San Antonio - Vergara'),
    b('238', '5', 'Ramal Haedo Barrio Sere - Santa Rosa'),
  ]),
  linea('242', [
    b('242', 'a', 'A - Liniers por Larrea - Moron'),
    b('242', 'b', 'B - Ciudad Evita por Igr. Brian - Barrio Bid'),
    b('242', 'barrio-abadia', 'Barrio Abadia por Don Bosco'),
    b('242', 'c', 'C - Barrio El Cortijo'),
    b('242', 'd', 'D - Moron'),
    b('242', 'e', 'E - Haedo'),
    b('242', 'f', 'F - Barrio Los Pinos'),
  ]),
  linea('243', [
    b('243', '1', 'Lomas de Zamora'),
  ]),
  linea('244', [
    b('244', '1', 'Don Torcuato'),
  ]),
  linea('247', [
    b('247', '2', '2 - Estacion Fiorito'),
    b('247', '5', '5 - Estacion Fiorito'),
    b('247', '7', '7 - Estacion Fiorito'),
  ]),
  linea('252', [
    b('252', 'c', 'C - Carapachay'),
    b('252', 'p', 'P - El Palomar'),
  ]),
  linea('253', [
    b('253', '1', 'Libertad'),
  ]),
  linea('257', [
    b('257', '1', 'San Francisco Solano'),
    b('257', '2', 'Servicio Circular - Monteverde'),
    b('257', '3', 'Servicio Circular - Pasco'),
  ]),
  linea('263', [
    b('263', 'negro', 'Negro - Estacion Burzaco'),
    b('263', 'rojo', 'Rojo - Estacion Burzaco'),
    b('263', 'verde', 'Verde - Estacion Burzaco'),
  ]),
  linea('266', [
    b('266', '1', '1 - Cementerio de Avellaneda'),
    b('266', '2', '2 - Est. Rafael Calzada'),
    b('266', '4', '4 - Rivadavia por Burzaco'),
    b('266', '5', '5 - Est. Florencio Varela'),
    b('266', 'mosconi', 'Mosconi'),
    b('266', 'villa-alcira', 'Villa Alcira'),
  ]),
  linea('269', [
    b('269', '1', 'Cruce Castelar'),
    b('269', '2', 'Est. Lemos por Cruce - Hospital'),
    b('269', '3', 'Est. Moreno por Castelar'),
    b('269', '4', 'Est. San Miguel por Lomas de Marilo'),
    b('269', '5', 'Las Catonas por Gaona - Marilo'),
    b('269', '6', 'San Miguel por Castelar'),
    b('269', '7', 'San Miguel por Gaona - Marilo'),
    b('269', '8', 'Villa Leon por Bacacay'),
  ]),
  linea('271', [
    b('271', '1', '1 - Quilmes Oeste'),
    b('271', '2', '2 - Quilmes Oeste'),
    b('271', '5', '5 - Quilmes Oeste'),
    b('271', 'a-lanus', 'A - Est. Lanus'),
    b('271', 'a-lanus2', 'A - Lanus por Est. Rafael Calzada - Barrio San Jose'),
    b('271', 'd', 'D - Avellaneda'),
    b('271', 'p', 'P - Avellaneda por D. Alvarez - Camino Gral. Belgrano'),
  ]),
  linea('277', [
    b('277', '1', 'Univ. de Lomas de Zamora'),
  ]),
  linea('278', [
    b('278', '436b', '436 B - Est. Lomas de Zamora'),
    b('278', 'a', 'A - Balneario de Quilmes'),
    b('278', 'b', 'B - Barrio San Jose'),
    b('278', 'c', 'C - San Francisco Solano'),
    b('278', 'p', 'P - Lanus'),
    b('278', 's', 'S - Barrio San Jose'),
    b('278', 's2', 'S por Falucho - Villa la Florida'),
    b('278', 'w', 'W - Villa la Florida por San Martin - Eucaliptus'),
  ]),
  linea('281', [
    b('281', 'l', 'L - Balneario de Quilmes'),
  ]),
  linea('283', [
    b('283', 'b1', 'B1 - Ingeniero Budge'),
    b('283', 'b2', 'B2 - Baln. Villa Albertina'),
    b('283', 'b3', 'B3 - Puente de La Noria'),
  ]),
  linea('284', [
    b('284', '1', 'Altos de Castillo'),
    b('284', '2', 'Rafael Castillo por Mosconi'),
  ]),
  linea('291', [
    b('291', '1', 'Dique Lujan'),
    b('291', '2', 'Las Orquideas por Amancay'),
    b('291', '3', 'Pilar por Jumbo'),
    b('291', '4', 'Term. de Omnibus de Pilar'),
  ]),
  linea('293', [
    b('293', '2', '2 - Barrio El Dorado por Mitre'),
    b('293', 's', 'S - Don Orione'),
    b('293', 's2', 'S - San Francisco Solano'),
    b('293', 't2', 'Troncal 2 - Barrio El Dorado'),
  ]),
  linea('295', [
    b('295', '1', '1 - Wilde por Madariaga'),
    b('295', '2', '2 - Wilde por Coplinco - Bouchard'),
    b('295', '4', '4 - Pte. Pueyrredon por Magan'),
    b('295', '5', '5 - Pte. Pueyrredon por Cordoba'),
  ]),
  linea('298', [
    b('298', '1', 'Liniers por San Martin'),
    b('298', '2', 'Moron por Celina - Nazca - Hospital de Niños'),
    b('298', '3', 'Moron por Ruta 4'),
    b('298', '4', 'Moron por Villegas - Mercado Central'),
  ]),
  linea('299', [
    b('299', 'a', 'A - Banfield'),
    b('299', 'c', 'C - Est. Banfield por Almeyra'),
    b('299', 'l', 'L - Banfield Bv. Armesti'),
    b('299', 'm', 'M - Est. Banfield'),
    b('299', 's', 'S - San Jose Av. Eva Peron'),
  ]),
  linea('300', [
    b('300', 'a', 'A - Bosques por Antartida'),
    b('300', 'b1', 'B1 - Bosques'),
    b('300', 'c', 'C - Bosques'),
  ]),
  linea('302', [
    b('302', '1', 'Moron por Gaona'),
    b('302', '2', 'Pte. Liniers por Gaona'),
  ]),
  linea('303', [
    b('303', '1', 'El Talar'),
  ]),
  linea('306', [
    b('306', '1', 'Barrio Esperanza - Pte. de la Noria'),
    b('306', '2', 'El Zaizar - Pte. de la Noria'),
    b('306', '3', 'Ezeiza - Pte. de la Noria por Av. Fair'),
    b('306', '4', 'Pte. de la Noria por Av. Fair'),
    b('306', '5', 'Spegazzini - Pte. de la Noria'),
    b('306', '6', 'Transradio - Pte. de la Noria'),
    b('306', '7', 'Transradio - San Justo'),
    b('306', '8', 'Troncal - San Justo'),
  ]),
  linea('310', [
    b('310', '1', 'Barrio Libertador'),
  ]),
  linea('312', [
    b('312', '01', '01 - Est. Ituzaingo'),
  ]),
  linea('314', [
    b('314', 'amarillo', 'Amarillo - Puente Saavedra por Munro'),
    b('314', 'azul', 'Azul - Villa Ballester'),
    b('314', 'rojo', 'Rojo - Puente Saavedra'),
  ]),
  linea('315', [
    b('315', '1', 'El Talar'),
  ]),
  linea('317', [
    b('317', '1', 'Crovara y Cristiania'),
    b('317', '2', 'Isidro Casanova'),
  ]),
  linea('318', [
    b('318', 'a', 'A - Claypole por Adrogue'),
    b('318', 'b', 'B - Claypole por Burzaco'),
    b('318', 'm', 'M - Monte Grande por Segui'),
    b('318', 'r', 'Rodriguez - Virgilio'),
  ]),
  linea('320', [
    b('320', '1', 'Estacion Martin Coronado'),
  ]),
  linea('321', [
    b('321', '1', 'Barrio Marina'),
  ]),
  linea('322', [
    b('322', '1', 'Marcos Paz - Moron'),
    b('322', '2', 'Merlo - Marcos Paz'),
    b('322', '3', 'Merlo - Unidad Penitenciaria U2'),
  ]),
  linea('324', [
    b('324', '1', '1 - Ingeniero Allan'),
    b('324', '2', '2 - Bosques'),
    b('324', '3', '3 - La Carolina'),
    b('324', '4', '4 - Auchan - La Carolina'),
    b('324', '5', '5 - Km 56 de Au. Ruta Provincial 2'),
    b('324', '6', '6 - El Pato'),
    b('324', '9', '9 - Auchan - Bosques'),
    b('324', '11', 'Cartel 11 - Estacion Quilmes'),
    b('324', '16', '16 - Estacion Varela'),
  ]),
  linea('325', [
    b('325', '1', 'Laferrere'),
    b('325', '2', 'San Justo - Laferrere'),
  ]),
  linea('326', [
    b('326', '1', 'Av Beirá y Gral Paz'),
    b('326', '2', 'El Palomar'),
    b('326', '3', 'Est. Tropezón'),
    b('326', '4', 'Palomar'),
  ]),
  linea('328', [
    b('328', 'a', 'A - Estacion San Martin por Triunvirato'),
    b('328', 'b1', 'B - 3 de Febrero por Caseros'),
    b('328', 'b2', 'B - Estacion San Martin por Santos Vega'),
    b('328', 'c', 'C - 3 de Febrero por P. Podesta'),
  ]),
  linea('333', [
    b('333', '1', 'Estacion Olivos'),
  ]),
  linea('336', [
    b('336', '1', 'Estacion Paso del Rey'),
  ]),
  linea('338', [
    b('338', '1', 'Ex 54 - Cruce de Lomas - Ramos Mejia'),
    b('338', '2', 'Fracc. La Plata - Moron'),
    b('338', '3', 'Fracc. La Plata - Moron por Adrogue'),
    b('338', '4', 'Fracc. La Plata - San Justo'),
    b('338', '5', 'Fracc. La Plata - San Justo por Adrogue'),
    b('338', '6', 'Fracc. Tablada - San Isidro por Camargo'),
    b('338', '7', 'Fracc. Tablada - San Isidro por R4'),
    b('338', '8', 'San Isidro por Adrogue'),
    b('338', '9', 'San Isidro por Camargo'),
    b('338', '10', 'San Isidro por Camino Centenario - R4'),
    b('338', '11', 'San Isidro por Llavallol - Camargo - Carcel de Olmos'),
    b('338', '12', 'San Isidro por Pasco - Carcel de Olmos'),
    b('338', '13', 'San Isidro por camino del Buen Ayre'),
    b('338', '14', 'Troncal - San Isidro por Pasco - R4'),
  ]),
  linea('341', [
    b('341', '1', 'Av. Constituyentes y Acceso Norte'),
    b('341', '2', 'Cabaña - Km 30'),
    b('341', '3', 'Los Polvorines - Don Torcuato - San Miguel - Grand Bourg'),
    b('341', '4', 'Olivos - Fonavi - Grand Bourg'),
  ]),
  linea('343', [
    b('343', '1', 'Carupa por Lourdes'),
    b('343', '2', 'Tigre por Lourdes'),
    b('343', '3', 'x 289 Liniers - San Martin'),
    b('343', '4', 'x 289 Ramos Mejía - San Martin'),
    b('343', '5', 'x 304 - San Isidro'),
  ]),
  linea('354', [
    b('354', 'b', 'B - Lanús'),
    b('354', 'f', 'F - Valentín Alsina'),
  ]),
  linea('365', [
    b('365', '1', 'Derqui x Lamas - Panamericana'),
    b('365', '2', 'Derqui x San Atilio - Panamericana'),
    b('365', '3', 'Lujan x Canal/Cruce - Sab y Dom'),
    b('365', '4', 'Lujan x Panamericana - Sab y Dom'),
    b('365', '5', 'Stefani por Canal/Cruce'),
    b('365', '6', 'Stefani por San Miguel'),
    b('365', '7', 'Stefani x Panamericana x Hospital'),
  ]),
  linea('371', [
    b('371', 'a', 'A - Don Torcuato por Virreyes - Acassuso'),
    b('371', '2', 'Don Torcuato - Bella Vista por Maipu'),
    b('371', '3', 'Don Torcuato - Pablo Nogues por Sucre'),
    b('371', '4', 'Est. Don Torcuato - Puente Melo Florida'),
    b('371', '5', 'Fracc. Don Torcuato - Los Polvorines por Sucre'),
    b('371', '6', 'Por Barrio Aviacion - Don Torcuato'),
    b('371', '7', 'Por Calle 8 - Est. Boulogne Sur Mer'),
    b('371', '8', 'Por Fate - Est. Boulogne Sur Mer'),
  ]),
  linea('372', [
    b('372', '1', 'Bosques'),
  ]),
  linea('378', [
    b('378', '1', 'Barrio Independencia por San Martin - C. Casares - Spiro'),
    b('378', '2', 'Laferrere por Pringles - Km 24.7'),
    b('378', '3', 'Laferrere por San Martin - Borgward'),
    b('378', '4', 'Laferrere - Gonzales Catan por Pringles - Km 26'),
    b('378', '5', 'Rafael Castillo por San Martin'),
    b('378', '6', 'Semirapido - Est. Ciudadela Spiro'),
    b('378', '7', 'Semirapido - Laferrere - Barrio Independencia'),
    b('378', '8', 'Semirapido - Spiro'),
  ]),
  linea('379', [
    b('379', '1', 'Los Polvorines'),
  ]),
  linea('382', [
    b('382', '1', 'Liniers - Ruta N° 3 Km 47.7'),
    b('382', '2', 'Pontevedra - Gral. Paz por Ruta 3'),
  ]),
  linea('384', [
    b('384', '2', '2 - Estacion Adrogue'),
  ]),
  linea('386', [
    b('386', '1', 'Jose Ingenieros'),
  ]),
  linea('390', [
    b('390', '1', 'Puente Liniers'),
  ]),
  linea('391', [
    b('391', '1', 'Barrio La Paz'),
    b('391', '2', 'Fracc. Jose C. Paz - San Atilio'),
    b('391', '3', 'San Atilio por Croacia'),
    b('391', '4', 'San Atilio por Oribe'),
  ]),
  linea('392', [
    b('392', '1', 'Merlo'),
  ]),
  linea('395', [
    b('395', '1', 'Estacion Ituzaingo - Castelar - San Alberto'),
    b('395', '2', 'Santa Cecilia'),
    b('395', '3', 'Villa Las Naciones'),
  ]),
  linea('403', [
    b('403', '1', 'Est. Florencio Varela'),
  ]),
  linea('405', [
    b('405', '1', 'Ingeniero Budge'),
  ]),
  linea('406', [
    b('406', '1', 'Barrio San Jose'),
    b('406', '2', 'Est. Ramos Mejia - Mendeville - Est. Lomas'),
  ]),
  linea('407', [
    b('407', '1', 'Estacion Munro'),
  ]),
  linea('410', [
    b('410', '1', 'Cartel Lujan'),
    b('410', '2', 'Cartel Pilar por Ruta 8'),
    b('410', '3', 'Fracc. hasta Moreno'),
    b('410', '4', 'Rapido por Roca - Cruce Castelar - Moreno'),
    b('410', '5', 'Semirapido por Camino Parque del Buen Ayre - Moreno'),
  ]),
  linea('414', [
    b('414', '1', 'Est. Florencio Varela'),
  ]),
  linea('418', [
    b('418', '1', 'Estacion Berazategui'),
  ]),
  linea('421', [
    b('421', '1', 'Avellaneda - Pte. Pueyrredon'),
    b('421', '2', 'Pte. de la Noria - Pavon y Mitre'),
  ]),
  linea('422', [
    b('422', '1', 'Barrio Luchetti - Acceso Country Club Banco Provincia'),
    b('422', '2', 'Lujan'),
  ]),
  linea('429', [
    b('429', '1', 'Cartel Lujan'),
    b('429', '2', 'Cartel Lujan - Fracc. hasta Moreno'),
    b('429', '3', 'Cartel Pilar por Ruta 8'),
    b('429', '4', 'Rapido - Moreno por Roca - cruce Castelar'),
    b('429', '5', 'Semirapido - Moreno por Cno. Parque del Buen Ayre'),
  ]),
  linea('430', [
    b('430', '1', 'Rincon de Milberg'),
  ]),
  linea('435', [
    b('435', '1', 'San Vicente'),
  ]),
  linea('437', [
    b('437', '1', 'Boulogne'),
    b('437', '2', 'San Isidro Bajo Troncal - Estacion Garin'),
  ]),
  linea('441', [
    b('441', '1', 'Barrio Nuevo - La Refalosa'),
    b('441', '2', 'Barrio San Alberto'),
    b('441', '3', 'Castelar - Villa Udaondo'),
    b('441', '4', 'Villa Angela'),
  ]),
  linea('443', [
    b('443', '2', '2 - Barrio Libertador'),
    b('443', '3', '3 - Villa Club'),
    b('443', '4', '4 - Jufre'),
  ]),
  linea('446', [
    b('446', '1', 'Estacion Avellaneda'),
  ]),
  linea('461', [
    b('461', '1', 'Villa Udaondo'),
  ]),
  linea('462', [
    b('462', '1', 'Estacion J. Newbery'),
  ]),
  linea('463', [
    b('463', '1', 'Acassuso - Barrio Cartero'),
    b('463', '2', 'Barrio Gaona - Jufre'),
    b('463', '3', 'Bustamante - Barrio Destino'),
  ]),
  linea('464', [
    b('464', '1', 'Bonorino - San Damian'),
    b('464', '2', 'Felix Frias'),
  ]),
  linea('500', [
    b('500', '1', 'Merlo - Barrio Lasalle'),
    b('500', '2', 'Merlo - Merlo Gomez'),
    b('500', '3', 'Merlo - Padua - Helvecia'),
    b('500', '4', 'Merlo - Padua - Petracci'),
    b('500', '5', 'San Antonio de Padua - Barrio Nuevo'),
    b('500', '6', 'San Antonio de Padua - El Ceibo'),
    b('500', '7', 'San Antonio de Padua - Pericon'),
    b('500', '8', 'San Antonio de Padua - Pontevedra'),
    b('500', '9', 'San Antonio de Padua - Rivadavia - Campanilla'),
    b('500', '10', 'San Antonio de Padua - San Lorenzo'),
  ]),
  linea('503', [
    b('503', '1', 'Arboleda por La Loma'),
    b('503', '2', 'Barrio Lambertucci por Estrada'),
    b('503', '3', 'Barrio Lambertucci por Tapia de Cruz'),
    b('503', '4', 'Barrio San Luis'),
    b('503', '5', 'Coprovi'),
    b('503', '6', 'Fracc. Escobar - Garin'),
    b('503', '7', 'Fracc. Escobar - Ingeniero Maschwitz'),
    b('503', '8', 'Garin - Barrio Fonavi'),
    b('503', '9', 'Loma Verde'),
  ]),
  linea('505', [
    b('505', '3', '3 - Est. Burzaco'),
    b('505', '4', '4 - Est. Adrogue'),
    b('505', '5', '5 - Burzaco'),
    b('505', '6', '6 - Claypole por Falucho'),
  ]),
  linea('506', [
    b('506', '1a', '1 - Glew - Gendarmeria - San Jose por Bynnon'),
    b('506', '1b', '1 - Glew - San Jose por Tapin'),
    b('506', '1c', '1 - San Jose por Hospital'),
    b('506', '1d', '1 - San Jose - Gendarmeria por Bynnon'),
    b('506', '3a', '3 - Adrogue - San Jose Servicio Nocturno'),
    b('506', '3b', '3 - Glew - San Jose por Tapin'),
    b('506', 'fracc', 'Cartel 1 - Fracc. Estacion Adrogue - San Jose'),
    b('506', 'claypole', 'Claypole - Adrogue'),
    b('506', 'ramal', 'Fracc. de los ramales 1 - Barrio Gendarmeria - Est. Glew'),
  ]),
  linea('514', [
    b('514', 'a', 'A - Barrio Lindo - Don Orione por Adrogue'),
    b('514', 'b', 'B - Loma Verde - Solano por Burzaco'),
    b('514', 'esther', 'Barrio Esther'),
    b('514', 'ruta4', 'Ruta 4 - Est. Burzaco'),
  ]),
  linea('520', [
    b('520', 'b', 'B - Lanus Oeste'),
    b('520', 'b1', 'B1 - Lanus Oeste'),
    b('520', 'c', 'C - Lanus Oeste'),
    b('520', 'd', 'D - Lanus Oeste Ex 529'),
  ]),
  linea('521', [
    b('521', '1', 'Villa Obrera'),
  ]),
  linea('522', [
    b('522', '1', 'Est. Monte Chingolo'),
  ]),
  linea('523', [
    b('523', 'e', 'E - Est. Remedios de Escalada'),
  ]),
  linea('526', [
    b('526', '1', 'Villa Ofelia'),
  ]),
  linea('527', [
    b('527', 'b', 'B - Corina por Cadorna'),
    b('527', 'c', 'C - Monte Chingolo'),
  ]),
  linea('532', [
    b('532', '1', '2 de Abril por Virgilio'),
    b('532', '2', 'J. M. De Rosas por De La Rivera - M. Pedraza'),
    b('532', '3', 'Santa Catalina por De La Rivera'),
  ]),
  linea('540', [
    b('540', 'a', 'A - Pte. de la Noria por Rivera Sud - Feria La Salada'),
    b('540', 'b', 'B - Pte. de la Noria por Igr. Budge'),
    b('540', 'c', 'C - Pte. de la Noria por Quesada'),
  ]),
  linea('541', [
    b('541', 'a', 'A - Barrio Sitra'),
    b('541', 'b', 'B - Barrio Centenario por Milan'),
  ]),
  linea('542', [
    b('542', '1', 'Pte. de la Noria'),
    b('542', '2', 'Pte. de la Noria por Rodriguez'),
  ]),
  linea('543', [
    b('543', '544', '544 - Santa Marta'),
    b('543', 'a', 'A - Est. Lomas - Facultad'),
    b('543', 'b', 'B - Est. Lomas - Parque Baron'),
    b('543', 'c', 'C - Por Quiroga - Carcel de Lomas'),
  ]),
  linea('548', [
    b('548', '1', 'Villa Albertina'),
  ]),
  linea('549', [
    b('549', '1', 'Cruce de Lomas'),
  ]),
  linea('550', [
    b('550', 'b', 'B - Puente de la Noria'),
    b('550', 'h', 'H - Puente de la Noria'),
    b('550', 'j', 'J - Puente de la Noria'),
  ]),
  linea('551', [
    b('551', 'a', 'A - Pte. de la Noria'),
    b('551', 'hosp', 'Hosp. Allende por Recondo'),
  ]),
  linea('552', [
    b('552', '1', 'Cruce de Lomas'),
  ]),
  linea('553', [
    b('553', '0', '0 - Olimpo'),
    b('553', 'e', 'E - Puente de la Noria'),
  ]),
  linea('561', [
    b('561', 'a', 'A - Universidad de Lomas'),
    b('561', 'b', 'B - Universidad de Lomas'),
  ]),
  linea('562', [
    b('562', 'b', 'B - Loma Verde por Frias'),
    b('562', 'c', 'C - Loma Verde por Mitre'),
  ]),
  linea('564', [
    b('564', '3', '3 - Estacion Temperley'),
    b('564', '9', '9 - Donato Alvarez y Pasco'),
  ]),
  linea('570', [
    b('570', '4a', '4 - Ex 373 Don Bosco'),
    b('570', '4b', '4 - Ex 373'),
    b('570', 'troncal', 'Troncal - Villa Corina - Villa Castellino'),
    b('570', 'uba1', 'U.B.A Avellaneda por Aguero - C. Larralde'),
    b('570', 'uba2', 'U.B.A Avellaneda por Mitre'),
  ]),
  linea('580', [
    b('580', '1', 'Ezpeleta Oeste'),
  ]),
  linea('582', [
    b('582', '1', 'Pellegrini'),
    b('582', '2', 'Pellegrini por 850 - San Francisco Solano'),
    b('582', '3', 'Pellegrini - Quilmes Oeste'),
  ]),
  linea('583', [
    b('583', '1', 'Villa Nueva Argentina'),
  ]),
  linea('584', [
    b('584', '1', 'Cruce Varela - Garage'),
  ]),
  linea('585', [
    b('585', '1', 'Balneario - 24 y Monteverde por 844'),
    b('585', '2', 'Balneario - Est. Solano por San Martin'),
  ]),
  linea('603', [
    b('603', '1', 'Barrio Maritimo'),
    b('603', '2', 'San Blas'),
    b('603', '3', 'La Porteña'),
    b('603', '4', 'Pueblo Nuevo'),
    b('603', '5', 'Parque Industrial'),
  ]),
  linea('619', [
    b('619', '1', 'El Pato'),
  ]),
  linea('620', [
    b('620', '1', 'Av. Gral Paz - Barrio La Floresta'),
    b('620', '2', 'Gonzales Catan - Barrio San Pedro'),
    b('620', '3', 'Gonzales Catan - Los Ceibos'),
    b('620', '4', 'Gonzales Catan - Los Ceibos por Dragones'),
    b('620', '5', 'Gonzales Catan - Scasso por Da Vinci'),
    b('620', '6', 'Gonzales Catan - Villa Dorrego'),
    b('620', '7', 'Km 36,5 - San Pedro'),
    b('620', '8', 'Km 39 - Barrio Esperanza'),
    b('620', '9', 'Luz y Fuerza por Laferrere - Scasso'),
    b('620', '10', 'RN 3 Km 29 - Barrio Independencia'),
    b('620', '11', 'RN 3 Km 30,7 - Villa Dorrego'),
    b('620', '12', 'RN 3 Km 31 - Los Ceibos'),
    b('620', '13', 'RN 3 Km 31 - Los Ceibos por Gonzales Catan'),
    b('620', '14', 'RN 3 Km 38 - Virrey del Pino por Gonzales Catan y Barrio Esperanza'),
    b('620', '15', 'RN 3 Km 47,7 - por Gonzales Catan y Barrio Esperanza'),
    b('620', '16', 'Ramos Mejia por Facultad - Villa Borgward'),
    b('620', '17', 'Ramos Mejia por Facultad - Villa Dorrego'),
    b('620', '18', 'Ramos Mejia por Gonzales Catan'),
    b('620', '19', 'Troncal Est. San Justo - RN 3 Km 47,7'),
  ]),
  linea('621', [
    b('621', '1', 'Liniers - Gonzales Catan - Pontevedra Km 29'),
    b('621', '2', 'Liniers - Scasso por Calderon de la Barca'),
    b('621', '3', 'Ramos Mejia - Barrio Esperanza Km 38 - Escuela N° 179'),
    b('621', '4', 'Ramos Mejia - Ciudad Evita'),
    b('621', '5', 'Ramos Mejia - Gonzales Catan Km 28 Talita'),
    b('621', '6', 'Ramos Mejia - La Foresta Km 36,8'),
    b('621', '7', 'Ramos Mejia - Villa Scasso por Da Vinci'),
  ]),
  linea('622', [
    b('622', '1', 'Gonzales Catan - San Mariano por Oro Verde'),
    b('622', '2', 'Gral Paz Villa La Union Km 26 - El Porvenir'),
    b('622', '3', 'Gral. Paz - San Mariano'),
    b('622', '4', 'Laferrere - Villa La Union'),
    b('622', '5', 'Lomas del Mirador - Barrio Dorrego por Cristiania'),
    b('622', '6', 'Villa La Union Km 26 - Barrio Dorrego'),
  ]),
  linea('624', [
    b('624', '1', 'Barrio Bid - Hosp. de Niños'),
    b('624', '2', 'Por Barrio Central - Atalaya - Cementerio por Mocoreta'),
    b('624', '3', 'Ramos Mejia - Cementerio por Leon Gallo'),
    b('624', '4', 'San Justo - Barrio Los Pinos'),
  ]),
  linea('628', [
    b('628', '1', 'Est. Sanchez de Mendeville - Aldo Bonzi'),
  ]),
  linea('630', [
    b('630', '1', 'Gonzales Catan - Av. Crovara y Av. Gral. Paz por Barrio San Alberto'),
    b('630', '2', 'Gonzales Catan - Av. Crovara y Av. Gral. Paz por Laferrere'),
    b('630', '3', 'Gonzales Catan - Av. Crovara y Av. Gral. Paz por Victor Martinez'),
  ]),
  linea('634', [
    b('634', '1', 'El Palomar - Por Moron - Don Bosco - Barrio San Juan'),
    b('634', '2', 'Moron por Alessandri'),
  ]),
  linea('635', [
    b('635', '1', 'Barrio San Francisco'),
  ]),
  linea('670', [
    b('670', 'amarillo', 'Cartel Amarillo - Parque San Martin - Est. San Martín'),
    b('670', 'blanco', 'Cartel Blanco - Loma Hermosa - Villa Lynch'),
    b('670', 'naranja', 'Cartel Naranja - Villa Hidalgo - Est. San Martín'),
    b('670', 'rojo', 'Cartel Rojo - Libertador - Est. San Martín'),
    b('670', 'verde', 'Cartel Verde - por Ballester - Est. San Martín'),
  ]),
  linea('707', [
    b('707', 'amarillo', 'Amarillo'),
    b('707', 'azul', 'Azul'),
    b('707', 'desdob-amarillo', 'Desdob. del Ramal Amarillo - Club Nautico San Isidro'),
    b('707', 'desdob-azul', 'Desdob. del Ramal Azul'),
    b('707', 'rojo', 'Rojo'),
    b('707', 'verde', 'Verde'),
    b('707', 'blanco', 'x 700 - Blanco - Villa Adelina'),
    b('707', 'rojo2', 'x 700 - Rojo - Boulogne'),
  ]),
  linea('710', [
    b('710', '1', 'Canal San Fernando - Villa Jardin'),
    b('710', '2', 'Fate - Barrio del Carmen'),
    b('710', '3', 'San Fernando - Victoria'),
    b('710', '4', 'Victoria - San Fernando'),
    b('710', '5', 'Virreyes - Carupa'),
  ]),
  linea('720', [
    b('720', '1', 'Alte. Brown - Torcuato'),
    b('720', '2', 'Alte. Brown x 197 - Torcuato'),
    b('720', '3', 'Carupa - R 27 - Barrio El Arco'),
    b('720', '4', 'Carupa - R 27 - Cementerio Benavidez - Fca. Ford'),
    b('720', '5', 'Carupa - R 27 - S.O.E.V.A'),
    b('720', '6', 'Carupa - R 27 - Villa La Ñata - Dique Lujan'),
    b('720', '7', 'Carupa por Junin - Ford'),
    b('720', '8', 'Carupa por Tigre x 197 - San Pablo - Torcuato'),
    b('720', '9', 'Carupa x Tigre - Barrio Las Tunas - Barrio Rojas'),
    b('720', '10', 'Torcuato por Chile x Larralde'),
  ]),
  linea('721', [
    b('721', '1', '1 - Bº La Paloma - Pacheco - Talar por Ruta 197'),
    b('721', '2', '2 - Bº San Lorenzo - R. Mazza - El Zorzal por Av. Larralde'),
    b('721', '3', '3 - Bº Los Troncos - Pacheco - Talar por 25 de Mayo'),
    b('721', '4', 'Calle 5 - Carupa'),
    b('721', '5', 'Puerto de frutos - Troncos de Talar'),
  ]),
  linea('723', [
    b('723', '1', 'Aviacion por Km 26'),
    b('723', '2', 'Bancalari x 202 - Hospital de Pacheco'),
    b('723', '3', 'Los Dados - Escuela N° 37 - Est. Pacheco'),
  ]),
]
